### ISSUE TITLE
"404 - Page not found" for React: Access Props Using this.props challenge get hint

### ISSUE THREAD

**Issue by prokawsar** [freeCodeCamp/guide#10094]
In challenge [React: Access Props Using this.props](https://guide.freecodecamp.org/certifications/front-end-libraries/react/access-props-using-this-props) the **Get a Hint** link returns 404 error.

Here is "Page not found"  [Link](https://guide.freecodecamp.org/certifications/front-end-libraries/react/access-props-using-this-props)

**Comment by Asjas** [comment]
The [folder](https://github.com/freeCodeCamp/guide/tree/master/src/pages/certifications/front-end-libraries/react/access-props-using-this.props) is named incorrectly. That is why it's causing the 404 error. The words in a folder must be separated with a hyphen `-`.

Whoever wants to fix this should rename the folder to match the correct folder naming structure.

**Comment by MarkPuchalaII** [comment]
I'm on it.
I've pulled up the Challenge Page that needs an update.
Now I just need to find where it is in the GitHub repository so I can edit it..

**Comment by skprabhanjan** [comment]
@MarkPuchalaII , just wanted to know the status! 
I have a PR ready but giving you dibs on this :)

**Comment by MarkPuchalaII** [comment]
I actually got stuck on finding the darn page in the repository.
I’m totally up to hand over the PR to you if you can help me understand how to locate a challenge page like this one within the Github Repository.

  - -  Mark Puchala 2/

**Comment by skprabhanjan** [comment]
https://github.com/freeCodeCamp/guide/tree/master/src/pages/certifications/front-end-libraries/react/access-props-using-this.props
This was the file which had to renamed to **access-props-using-this-props**

**Comment by MarkPuchalaII** [comment]
Oh, wow. I didn't think to change the file's name. 
I was thinking to change the challenge's URL button the whole time.
Thanks for the insight!!
