### ISSUE TITLE
Stub on micro controllers?

### ISSUE THREAD

**Issue by rithvikp1998** [freeCodeCamp/guide#10197]
Should we have a stub on working with commonly used microcontrollers like Arduino, Raspberry pi, beagle bone etc?

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by BrodyUnderwood1** [comment]
Not trying to be nit-picky here but none of those are technically microcontrollers.  Seeing as the point of these guides is to inform maybe we could rename this to something more fitting?  The pi and beagle boards don't even have microcontrollers on them. "Arduino" is a name for both a dev environment and a number of boards that have microcontrollers on them (but aren't technically microcontrollers themselves).
