### ISSUE TITLE
Stub on React's context api

### ISSUE THREAD

**Issue by pratik-chakravorty** [freeCodeCamp/guide#10223]
I think there should be a stub for the new context api in react. 

---

> ✅️ By submitting this issue, I have verified the following

- [ ] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by ezioda004** [comment]
Hi @pratik-chakravorty,
You're welcome to add an article for Context API!
