### ISSUE TITLE
"404 - Page not found" for React: Use Array.map() to Dynamically Render Elements Challenge - Get Hint

### ISSUE THREAD

**Issue by therealistfredy** [freeCodeCamp/guide#10259]
In challenge [React: Use Array.map() to Dynamically Render Elements](https://learn.freecodecamp.org/front-end-libraries/react/use-array-map-to-dynamically-render-elements) the **Get a Hint** button returns a _404_ error.

[The broken link](https://guide.freecodecamp.org/certifications/front-end-libraries/react/use-array-map-to-dynamically-render-elements)

[The correct link](https://guide.freecodecamp.org/certifications/front-end-libraries/react/use-array.map-to-dynamically-render-elements/)

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
To anyone picking this up, the incorrectly named folder in [the guide](https://github.com/freeCodeCamp/guide/tree/master/src/pages/certifications/front-end-libraries/react/use-array.map-to-dynamically-render-elements) should be renamed to match [this](https://guide.freecodecamp.org/certifications/front-end-libraries/react/use-array-map-to-dynamically-render-elements).

**Comment by skprabhanjan** [comment]
@Asjas , Can I fix every file under this that has this kind of error ?
I see a few files named like this.

**Comment by Asjas** [comment]
Sure go ahead :+1: 

There are quite a few so that would be great.
