### ISSUE TITLE
Suggestion: show article path in search

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/guide#206]
Currently, when running a search, it can be difficult to tell what category an article belongs to. Having a breadcrumb that shows the path would be really helpful:

```
Computer Science -> Algorithms -> B Trees
```
Seeing that would add a lot of value on top of only the title and an excerpt.

**Comment by Bouncey** [comment]
This would be easy enough to implement, but we would have to account for challenges on `freecodecamp.org`, youtube videos and eventually medium articles, maybe even forum posts?

It could be a conditional component? 

```
if the url is relative => show breadcrumbs
```

**Comment by QuincyLarson** [comment]
Yes - we could also just say (YouTube) or (Medium) in place of the breadcrumbs in those situations.

Forum posts are growing so rapidly, and there is a lot of redundancy there. If we were to just add them to the search, they'd probably crowd everything else out in the search results. I think for now we should treat the forum as a separate place with its own built-in search engine.

**Comment by Bouncey** [comment]
Great. So the spec is:

If the search result is an article from the guide show breadcrumbs
else denote where the source of the result is from (each result has a `_index` prop which will help with this, you can see how it is used in `src/pages/search/components/Results.jsx`)

**Comment by QuincyLarson** [comment]
@Bouncey That sounds like a well-reasoned approach.

**Comment by dhanushuUzumaki** [comment]
@Bouncey Has anyone started looking at this? Else I would like to give it a try.

**Comment by systimotic** [comment]
@dhanushuUzumaki We did add breadcrumbs to the pages, but not to the search page. The page breadcrumb component is at `src/pageComponents/Breadcrumb.jsx`. You're welcome to give this a go, I'd love to see this implemented!

**Comment by dhanushuUzumaki** [comment]
@systimotic  Thanks, I'll pick it right away.

**Comment by systimotic** [comment]
@dhanushuUzumaki Awesome! Keep us updated 🙂

**Comment by dhanushuUzumaki** [comment]
@systimotic Raised a PR for this #710

**Comment by dhanushuUzumaki** [comment]
@Bouncey @systimotic Raised a new PR #751

**Comment by Nirajn2311** [comment]
Is this issue closed?

**Comment by QuincyLarson** [comment]
@Bouncey I saw you merged a PR - has this been deployed to Search yet?
