### ISSUE TITLE
Add ability to sort search results by type (i.e. video, medium, guides...)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/guide#226]
Hey! I was talking to Quincy and Berkeley and we thought it would be good to be able to sort search results by type such as video, Medium, or guides.

**Comment by Bouncey** [comment]
Sounds good to me, any idea on filtering technique? 
I like the github filters like `is:issue commenter:bouncey <search term>` so for us it could be `type:youtube Beau is awesome`

Or we could use checkboxes, but I think that will take away from the dynamic search-ahead thing we have going on.

I am also very open to suggestions.

**Comment by beaucarnes** [comment]
Yeah, I think you have a good idea of using filters like `type:youtube`. We have to make sure to document the options somewhere. What other options could there be besides 'type'? How hard would it be to associate an author with items? It may be helpful, especially when looking for medium articles.

**Comment by Bouncey** [comment]
It's shouldn't be too difficult, I'm sure medium gives us this in the rss feed, youtube might as well, but the chances are with youtube is the author will always be freeCodeCamp.
