### ISSUE TITLE
Add "last updated" metadata to articles

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/guide#240]
If possible, I think it would be good to add "Last Updated: ..." information on the articles' pages to get a sense of how up-to-date the information is.

We could get that information from either maybe a GitHub API or use `git log -1 file-name.md` and then inject that information on the page. Although, that might not scale well.

Thoughts?

**Comment by Bouncey** [comment]
I would be reluctant to show a last updated date, as it could make the information look stale? I am open to a discussion though

**Comment by erictleung** [comment]
@Bouncey that's a fair point. The reason I suggested it was because I was looking through some of the articles there and was wondering how up to date the content was.

I understand that sometimes content doesn't change much (e.g. branching in git). However, for more modern topics, it might be nice to see current information.

An analogy for this might be looking at different GitHub repositories. If it hasn't been updated in a long time, it might not be the best to rely on. Of course, some older software is dependable. But at least you can now make that assessment.

Just my two cents on ideas to improve the experience of reading the guides. Great work on getting it up and going :+1: 

Anyways, I'll keep this open for people to comment. No hurt feelings if this doesn't get approved.

**Comment by jamesjpk123** [comment]
I think this would be a great idea! With the "everchanging" state of programming, it would be a relief to know if an article was last updated. If we do this, to fix the "stale" issue, if an article has gone 3 months without being "reviewed" by a person, it can automatically be tagged stale, and someone can review the accuracy of the information. So by the end, we would have a "last updated" and "Last reviewed" part of the article. Or even better, just put in the "last reviewed" part, so we only need to work with one date.
