### ISSUE TITLE
Create a collapsible menu for smaller screen sizes

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guide#298]
The specs for this are open to change on review

- The collapsible menu and the current SideNav component are never rendered together
- Ideally a breakpoint will determine which menu is rendered
- The collapsible menu will default to closed
- You are not restricted to the existing components we have in `src/LayoutComponents/nav`, you can create your own if required👍

**Comment by ChaituVR** [comment]
#8119 Closes this
