### ISSUE TITLE
Add chrome/firefox web developer tool guide

### ISSUE THREAD

**Issue by xuhang57** [freeCodeCamp/guide#302]
Currently, under the developer tools guide,  https://guide.freecodecamp.org/developer-tools, a guide for how to use chrome/firefox web developer tool would be nice.

**Comment by Bouncey** [comment]
Sounds good to me :+1:

**Comment by Manish-Giri** [comment]
Can I take this up? Haven't contributed to `guides` before.

**Comment by xuhang57** [comment]
@Manish-Giri please go ahead and just ping this issue in your PR description. Thanks!

**Comment by mokutsu** [comment]
Hi all, I noticed this issue was from a few weeks ago, was wondering if I could help out at all!

**Comment by xuhang57** [comment]
@mokutsu  please go ahead! Thanks for working on this 👍

**Comment by johnkennedy9147** [comment]
article has been created and updated by multiple PRs so closing this issue
