### ISSUE TITLE
Translation to other Languages 

### ISSUE THREAD

**Issue by ahasna** [freeCodeCamp/guide#310]
Are you guys considering to translate your content to other languages? I am happy to start doing this to my language Arabic

**Comment by erictleung** [comment]
@ahasna thanks for the issue! This could be great. Let's hear from others on how we could or should implement translations.

cc/ @QuincyLarson @Bouncey

**Comment by JuanLuisCh** [comment]
I'm able to start translating into Spanish, but, first we need to solve one thing. How to add the articles in different languages without being redundant

**Comment by evaristoc** [comment]
@JuanLuisCh @ahasna:

The following below are my personal opinions:

It is important to take in account what @systimotic mentioned in the Contributors channel: there is currently no plans to make the translations available as the first objective would be to settle the existing project. However IMO translating while the material in English is produced would be a big advantage and will easy the process of versions in different languages when the technical challenges get solved.

So I am, like @erictleung and many others, absolutely positive about your initiative.

If your initiative project receives a positive feedback I would suggest the following:
1. Start getting organized. You might end up been the leaders of possible translation efforts and focal points if more people want to get involved or need information. Prepare to organize the help and a translation plan, so look for info about how to manage a small team.
2. Establish the targets. In my opinion, it would make more sense if the translation team focus on the technically easiest parts first? Focus on an audience that would benefit for start learning the basics in your countries. Example: SCHOOLS (children), computer-illiterate audience or organic searches (like looking for wikipedia article in your native language).
3. Think on the translations as an extension not only for FCC course, but for ANY existing online and OFFLINE course, so it would be great if the selection of the translated material reflect the needs of your target country.
4. I would invite you to suggest material in English that could benefit your audiences.

If you start translating EVERY material you can:
1. Waste a lot of effort on material that might not reach your target audience, making it less effective
2. It will be harder for you and any team built around the translation effort.

@JuanLuisCh it could be redundant if your target audience has already English as language. The effort should be made on revealing information to an audience for which English is still not enough, that benefit for partial or total translation to understand the topics, and that could benefit from start learning web development. I can confirm that that target group exists.

**Comment by evaristoc** [comment]
@ahasna @JuanLuisCh 
Don't get me wrong regarding the point about "you might end up been leaders...". It is not that you will lead it. You can either lead or be part of a group of people working on it. So don't get scared. The fact is that you are the first I know who are proposing translations - there is no translation team at the moment.

But I would certainly suggest to plan your activities accordingly and be aware that the work might be for a future deployment, not immediate. Let's wait for the answer of Quincy or anyone with clearer idea about how to proceed.

**Comment by JuanLuisCh** [comment]
@evaristoc 
Thanks for the instructions, and observations. 

I'm already working on a little guide about technical translation, and thinking about the essential subjects to be translated, giving priority to subjects for audiences in early steps of learning the basics of coding, like HTML, CSS, JavaScript. As you say, there is a big group that benefits for partial or total translations to understand the topics. 

Also, I have a question, after finishing the guide (in spanish, how could I publish it?)

**Comment by JuanLuisCh** [comment]
I understand that translation is not a priority yet, but yes, would be great to start translating and organizing efforts towards this objective, and keep it "Invisible" until the right moment. 

The real challenge will be in the future incorporating multilingual options to the guide, how could we do it? @evaristoc

**Comment by Bouncey** [comment]
This can be done with routing I.e

`/en/JavaScript/array`
`/es/JavaScript/array`
`/ru/JavaScript/array`
`/de/JavaScript/array`

With a fallback of English 

These could be held in a `src/translations/` dir until such time that we make them live.

I'd be happy to put it on the roadmap, meaning it's not a priority right now, but it is something I would be interested in implementing in the future

**Comment by JuanLuisCh** [comment]
@Bouncey thanks!

**Comment by badasteroid** [comment]
I'll be happy to help the translation or to create a team that could do it for italian language :)

**Comment by juanluischaurant** [comment]
As stated weeks ago, I have been working on the technical translation (Right now it's only in Spanish) guide for Free Code Camp Guide articles, I need some orientation before going any further, where could I publish that guide?

**Comment by Gabogg07** [comment]
Hello @juanluischaurant i am interesting in working with you in translating to spanish. I dont know how much work is already done in this area, but i can always start at least with the readMe file. I checked that in the translation folder there is only Polish

**Comment by thecodingaviator** [comment]
> This can be done with routing I.e
> 
> `/en/JavaScript/array`
> `/es/JavaScript/array`
> `/ru/JavaScript/array`
> `/de/JavaScript/array`
> 
> With a fallback of English
> 
> These could be held in a `src/translations/` dir until such time that we make them live.
> 
> I'd be happy to put it on the roadmap, meaning it's not a priority right now, but it is something I would be interested in implementing in the future

@Bouncey , or should it be done the way China did it, by creating a totally new website? Have a look at https://freecodecamp.cn
