### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by texas2010** [freeCodeCamp/guide#347]
I would like to have night mode. thanks

**Comment by jamesjpk123** [comment]
Does the main freeCodeCamp website have night mode? If not, it would break away from freeCodeCamp's "style" to add night mode, unless night mode was added to both websites. Also, how would we distinguish between a user that want's night mode, and a user that doesn't automatically? You don't need a freeCodeCamp account to view the guide, and turning it on **every** single time you opened up the guide would be annoying. How would this work?

**Comment by meowwwls** [comment]
>  You don't need a freeCodeCamp account to view the guide, and turning it on every single time you opened up the guide would be annoying. How would this work?

@jamesjpk123 `localStorage` could be used to persist the theme choice. This of course would be lost each time the browser was restarted, but for users not logged in, this is the case for any site that allows preferences.  

I agree that night mode would be nice (for all of FCC, not just the guide), and Heydon Pickering actually recently wrote a wonderful [article](https://inclusive-components.design/a-theme-switcher/) about how to do this relatively painlessly using CSS filters.

**Comment by texas2010** [comment]
I would like to give this update. @m-henderson is working on this.

**Comment by thecodingaviator** [comment]
@texas2010 , @m-henderson , any update on this one?

**Comment by m-henderson** [comment]
@thecodingaviator yea, I have not made any progress. I have had a lot of other things that needed my attention. Would you guys like me to finish this up?

**Comment by thecodingaviator** [comment]
@m-henderson , it'd be great if we could have the feature :)
