### ISSUE TITLE
Texts pointing to links in several articles in javascript/array section

### ISSUE THREAD

**Issue by shovanch** [freeCodeCamp/guide#367]
It seems that, in few articles the anchor tags are closed at the end, hence the article text is pointing to the URL.

**Comment by Bouncey** [comment]
@shovanch can you point me to an example?

**Comment by shovanch** [comment]
@Bouncey See this one - https://guide.freecodecamp.org/javascript/standard-objects/array/array-prototype-every

The text is clickable. Don't know if that's a desired behaviour

**Comment by Bouncey** [comment]
oh wow!

`_normaliseArticles` has gone crazy!

These need to be corrected

**Comment by shovanch** [comment]
@Bouncey Can it be done within the README file?

**Comment by Bouncey** [comment]
I don't get what you mean?

**Comment by shovanch** [comment]
I mean closing the anchor tags properly by editing the README for the article.

**Comment by Bouncey** [comment]
Yes, this can be resloved by editing the `index.md` of the article :+1:

**Comment by shovanch** [comment]
OK, then I am on it. Just a question, is it ok fix multiple articles in a single PR?

**Comment by Bouncey** [comment]
yes please, as long as it is the same issue :+1:

**Comment by systimotic** [comment]
Thanks for finding and fixing these @shovanch! I found a few more articles that have the same issue (or something that seems similar):
- https://guide.freecodecamp.org/javascript/standard-objects/array/array-prototype-lastindexof (MSDN link)
- https://guide.freecodecamp.org/javascript/standard-objects/string/string-fromcharcode
- https://guide.freecodecamp.org/javascript/standard-objects/string/string-prototype-concat
- https://guide.freecodecamp.org/javascript/standard-objects/string/string-prototype-slice

**Comment by mabuyo** [comment]
I can fix the 4 articles you listed @systimotic if no one else is working on it. I'll do it in a single PR as well.

**Comment by systimotic** [comment]
@mabuyo That would be great!

**Comment by johnkennedy9147** [comment]
closed by #392 and #757
