### ISSUE TITLE
add counting sort algorithm

### ISSUE THREAD

**Issue by omurbekjk** [freeCodeCamp/guide#3988]

**Comment by pujanm** [comment]
Where we have to add this algorithm?

**Comment by omurbekjk** [comment]
@pujanm You can add other algorithms [here]( https://guide.freecodecamp.org/algorithms/sorting-algorithms)
Pull request for [this](https://github.com/freeCodeCamp/guides/pull/4012)

**Comment by domwakeling** [comment]
#4012 merged
