### ISSUE TITLE
Duplicate articles in CSS - CSS/Properties  

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guide#474]
Take `text-decoration` for example.

Duplicates should be removed :+1:

**Comment by dakotaclemenceplaza** [comment]
What about duplicating themes in javascript? For example 
https://guide.freecodecamp.org/javascript/multiply-two-numbers-with-javascript

Is there a need for such articles when there is arithmetic operations article 
https://guide.freecodecamp.org/javascript/arithmetic-operation-javascript

Should these be removed?

**Comment by johnkennedy9147** [comment]
Isn't this a duplicate of issue #410 Stub placeholder articles being left when article published.

**Comment by chiragbhansali** [comment]
@Bouncey How can we delete the folders of the duplicate properties. Do contributors have the permission to do so?

**Comment by systimotic** [comment]
@chiragbhansali [Doing this on your fork might work](https://github.com/blog/1545-deleting-files-on-github). I believe empty folders are removed automatically.

**Comment by johnkennedy9147** [comment]
@Bouncey @systimotic removed dupes text-decoration and background image property in pr #586 
I didnt spot any others but quite likely I've missed some with the volume of stubs and articles in css

**Comment by arhillis** [comment]
Is there anyway that articles can get added to the main repository more quickly so that we know which articles have already been modified and which ones are still stubs? I think that would cut down on the duplicates.

**Comment by thecodingaviator** [comment]
@arhillis , I do not think there's any way to dot hat yet, as all PRs need to be checked before being merged and these days especially a lot of them are being sent
