### ISSUE TITLE
Use of "JavaScript" and articles in titles

### ISSUE THREAD

**Issue by kevinsmithwebdev** [freeCodeCamp/guide#477]
I'm new here, but when I look at the list of JavaScript articles, several of their titles lead with "JavaScript...". This creates a confusing list as it seems to be out of alphabetical order, with entries starting with "j" sprinkled throughout. I would suggest not putting "JavaScript" in the title as it is redundant because we are in the JavaScript folder.

This may have also lead to some accidental duplication, for example there is an entry for "JavaScript for Loop" and "For Loops". Also there is "For in" and "JavaScript Forin Loop".

Additionally, I would suggest avoiding starting titles with articles (a, an, the), as in "The JavaScript Continue Statement" and "The Random Method". I would think that the key word of the article (that being defined) should be the first word in the title to create a more visually comprehensible list.

This is the list of titles as it stands now on the live site:

```
Advantages and Disadvantages of JavaScript
Angularjs Interview Questions
JavaScript Arguments
Arithmetic Operation JavaScript
JavaScript Assignment Operators
JavaScript Boolean
JavaScript Break Statement
JavaScript Callback Functions
Classes in JavaScript
JavaScript Closures
JavaScript Code Block
Code Linting in JavaScript
Comparison and Logical Operators
JavaScript Comparison Operators
JavaScript Loops
Conditional Ternary Operators
The JavaScript Continue Statement
Converting Strings to Numbers
JavaScript Dowhile Loop
Error Handling and Try Catch Throw
JavaScript Falsy Values
For in
JavaScript for Loop
For Loops
JavaScript for of Loop
JavaScript Forin Loop
Form Validation
Function Closures
Function Invocation
JavaScript Functions List
JavaScript Get Timestamp
JavaScript Global Variables
Higher Order Functions
HTML DOM getElementById Method
HTML Dom Innerhtml Property
If Else Statements
The JavaScript Ifelse Statement
JavaScript Immutable Types
JavaScript Isloggedinasync
Location Object
Location Reload Method
Loops and Iteration
Manipulate JavaScript Objects
Manipulating Cookies
Multiply Two Numbers with JavaScript
Naming Convention for JavaScript
Numbers
Onclick Event
Onload Event
Operators
Output
Popup Boxes
Promises
Prototypes
Regular Expressions Reference
The JavaScript Return Statement
Scopes in JavaScript
Semicolons in JavaScript
JavaScript Strict Mode
Switch Statements
JavaScript Ternary Operator
The JavaScript Global Object
The HTML Dom
JavaScript Truth Table
The Random Method
this reference in JavaScript
Timing Events
JavaScript Truthy Value
Typeof
The JavaScript Undefined Primitive Value
Where to
JavaScript While Loop
Window Confirm Method
Window Location
Window Open Method
Window Setinterval Method
Window Settimeout Method
With
```

**Comment by Bouncey** [comment]
Thanks for the issue @ksjazzguitar 

For this to be rectified correctly:
- rename the containing folder for this article `/src/pages/javascript/javascript-ternary-operator` -> `/src/pages/javascript/ternary-operator`
- the title field in the front matter should also be editied
```
---
title: JavaScript Ternary Operator
---
```
becomes
```
---
title: Ternary Operator
---
```

**Comment by johnkennedy9147** [comment]
this ties in with issues #410 and #414 

On the naming of articles the Article Style Guide does list examples that include language:

> Here are some title examples:

    "HTML Lists"
    "CSS Borders"
    "JavaScript For Loop"

So I was taking that as appropriate naming for the changes I am making, however, I do agree that it is not helpful.

**Comment by johnkennedy9147** [comment]
@Bouncey @systimotic I think this issue can be closed now

**Comment by systimotic** [comment]
@johnkennedy9147 I still found a few instances when searching through the Javascript directory using this regex: `^title: [^\n]*(JavaScript)`. I'll leave this open until those are resolved.

**Comment by dhanushuUzumaki** [comment]
@systimotic Raise a PR for this #704.

**Comment by dhanushuUzumaki** [comment]
@systimotic @texas2010 Create a new PR #734 .

**Comment by palingheorghe** [comment]
@systimotic @Bouncey shouldn't we change the README.md file so we wouldn't encounter issues like this one? Right now the README is guiding new contributors to write their titles like all these initial ones we now changed. 
![extract from README.md](https://screenshots.firefox.com/zDRGZGyx0ix0QaN4/github.com)

**Comment by systimotic** [comment]
@palingheorghe I agree. I think that should be handled through https://github.com/freeCodeCamp/guides/issues/659. It's still waiting for a few more responses.

**Comment by johnkennedy9147** [comment]
this has been resolved via multiple PRs so closing issue
