### ISSUE TITLE
Standardize informational and source links

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/guide#492]
Only looking at the Javascript section for now, but I'm sure others may have this issue; it seems like the way links are added to articles varies wildly. Let's discuss on the Contributors room and add a recommendation to the style guide. I think we should also talk about how people add sources to articles.

Some are:
`[ MDN | MSDN ]`
[Example](https://guide.freecodecamp.org/javascript/return-statements)

Others are:
`MDN | MSDN`
[Example](https://guide.freecodecamp.org/javascript/forin-loop)

Others are:
`MSDN link`
`MDN link`
[Example](https://guide.freecodecamp.org/javascript/assignment-operators)

Still others are:
`The amazing MDN`
[Example](https://guide.freecodecamp.org/javascript/arithmetic-operation-javascript)

**Comment by HKuz** [comment]
Thanks for bringing this up @dhcodes - we should definitely agree on a format. In addition to updating the style guide, I think we could also include the suggested format as a comment in the stub template. That way, at least the person editing it the first time through sees the format. (I'd also suggest changing the heading level of the "More Information" section from level-4 to level-3).

I don't feel strongly about any of the examples, but perhaps the most flexible option is the third one? That way, other section that wouldn't link to the MDN, etc. (like machine learning, for example), could just list their relevant links with some short/descriptive link text.

**Comment by erictleung** [comment]
@dhcodes @HKuz I like inline citations similar to Wikipedia. Maybe without the colon too?

Example

```
JavaScript (JS) is a lightweight interpreted or JIT-compiled programming language with first-class functions [[MDN](https://developer.mozilla.org/en-US/docs/Web/javascript)].
```

so it will render as 

> JavaScript (JS) is a lightweight interpreted or JIT-compiled programming language with first-class functions [[MDN](https://developer.mozilla.org/en-US/docs/Web/javascript)].

Thoughts?

Otherwise, I'm okay with `Short description of resource: [source](link...)`.

**Comment by HKuz** [comment]
@erictleung - I like that style for in-line citations 👍  Sorry, I should have been a bit more clear, the format I noted above was for the "More Information:" section, it would look a bit goofy in other areas 😄

**Comment by erictleung** [comment]
@HKuz ah I see. For the "More information:" section, I'd suggest going with a list too. So something like this?

```
### More information

- Documentation for X thing: [MDN](link...)
- A good academic article for this thing: [Y University](link...)
```

**Comment by dhcodes** [comment]
I agree with both of you. Anyone is welcome to make the change to the readme or I will at some point tomorrow or the next day.

**Comment by dhcodes** [comment]
Revisiting this, I now think we should use the following:

```
#### More Information:

[History of Rust](https://en.wikipedia.org/wiki/Rust_(programming_language)#History)
[Rust Programming Language](https://www.rust-lang.org/en-US/)
[Introduction to Rust](https://doc.rust-lang.org/book/first-edition/getting-started.html)
```

These feel more like 'natural language' links to me. I'm probably making this more important than it needs to be but having worked through some PRs, it saves space/time to combine the link with the description of what it is, imho.

**Comment by HKuz** [comment]
Okay - we should make a final call on this - how about combining best of both worlds and taking @erictleung 's suggestion to keep the list format, but use @dhcodes 's combo of the link text with the description. So basically:

#### More Information:

- [History of Rust](https://en.wikipedia.org/wiki/Rust_(programming_language)#History)
- [Rust Programming Language](https://www.rust-lang.org/en-US/)
- [Introduction to Rust](https://doc.rust-lang.org/book/first-edition/getting-started.html)

I think the bullets make it slightly easier to read.

**Comment by dhcodes** [comment]
@HKuz do you want to make the PR to finish out your Hacktoberfest quest?

**Comment by HKuz** [comment]
@dhcodes - much appreciated and thank you! But @erictleung has an open PR for the README over in #621 - I say we just include this change in that PR for efficiency's sake 😄 I'll have to think of a good article to write to earn my free t-shirt... ✏️ ✅ 💥 👕

**Comment by erictleung** [comment]
@dhcodes @HKuz I totally forgot my PR 😅  I've obviously gotten busy the past several weeks. I'll update it right now.
