### ISSUE TITLE
[suggestion] SideNav width

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/guide#493]
I'm not a UI expert, but I think making the width of the sidenav be `col-md-3` looks a touch better than its current `col-md-4` because it puts the content more in the center and lines up nicely with the logo at the top. Thoughts? imho of course.

**Comment by systimotic** [comment]
@dhcodes I agree with your pros, but I also see some cons:
- Line length is longer, which isn't good for the reading experience
- Line length on the SideNav is shorter which means a lot more things wrap on multiple lines, which also isn't ideal.

**Comment by Ethan-Arrowood** [comment]
Check out the screenshots below for a comparison.
Column Width 3:
<img width="1439" alt="Width3" src="https://user-images.githubusercontent.com/16144158/30971432-dbd13d66-a435-11e7-992d-d39f3452797e.png">
Column Width 4:
<img width="1438" alt="Width4" src="https://user-images.githubusercontent.com/16144158/30971443-e4064f3a-a435-11e7-97c7-631a52e7b59b.png">
@dhcodes & @systimotic if you guys prefer the 3 column width I'd be happy to submit a PR. Its literally one byte difference :laughing:

**Comment by dhcodes** [comment]
We need a 3.5 ... lol. @systimotic based on @Ethan-Arrowood's screenshots, the line-length looks the same.

**Comment by Ethan-Arrowood** [comment]
FYI This was screenshot on a 15"MacBook Pro running Google Chrome at standard view

**Comment by systimotic** [comment]
😄 A 3.5 would be nice

Line length in the SideNav is definitely shorter. This is more noticeable when you go in another level:
![20170929_10-13-49_firefox](https://user-images.githubusercontent.com/7262039/31006923-09ecc1d8-a4ff-11e7-8a96-09a657596750.png)
![20170929_10-14-50_firefox](https://user-images.githubusercontent.com/7262039/31006929-0d71d488-a4ff-11e7-9574-47bfd25ab2c8.png)

In the screenshot, the line length of the content is the same. Only 11 out of 12 columns are used, however, so there's an empty column on the right, which really bothers me 😅

**Comment by dhcodes** [comment]
We could make the width of `col-md-4` be `30%` or something. It's not a big deal either way; just something I noticed.

**Comment by Bouncey** [comment]
We could roll our own grid...

🤔 

Or use a `.container-fluid` for the row that holds the side nav and content
