### ISSUE TITLE
Add guides for specific JavaScript frameworks

### ISSUE THREAD

**Issue by clang676** [freeCodeCamp/guide#494]
Any plans to add guides for specific JavaScript frameworks? 

Such as angular, Vue.js,  and react?

**Comment by erictleung** [comment]
@clang676 sure! We just need people to write them :smile:

**Comment by BitYog** [comment]
@erictleung 
1) What exactly do we need? 
2) Where do I add these guides? (which folder)

**Comment by johnkennedy9147** [comment]
Hi @erictleung @BitYog I am in the process of adding directories for Libraries and Frameworks under JavaScript, should get a PR submitted later today.  It is just the framework of directories and stubs, so if you want to make a start on the articles then just pop them into the appropriate folder when they are live.

**Comment by johnkennedy9147** [comment]
@systimotic @BitYog @erictleung I've submitted PR #630 creating directory structure and stubs for a few common frameworks and libraries

**Comment by dhanushuUzumaki** [comment]
Hi, If we are to write an article about a framework, should it be a single article containing a brief hello world intro to that framework or should we create subdirectories for each topic and add full explanation there?

**Comment by erictleung** [comment]
@BitYog 

1. Any JS frameworks you feel are worth mentioning
2. It appears that @johnkennedy9147 has gone ahead and made a `frameworks-and-libraries` subdirectory to put these in.

@johnkennedy9147 thanks for moving some of the articles around. I think that is in the right direction. Let's wait on others to comment cc/ @HKuz @systimotic @Bouncey 

@dhanushuUzumaki I think a quick introduction about them is good and then having more detailed explanations of specific functionality in other articles.

**Comment by dhanushuUzumaki** [comment]
Thanks @erictleung

**Comment by AkiraLaine** [comment]
Gonna be writing some Vue.js articles :smile:
