### ISSUE TITLE
Organize articles in Mathematics folder

### ISSUE THREAD

**Issue by chesun** [freeCodeCamp/guide#5175]
After going through the content in the Mathematics folder, it seems like it can be roughly categorized under Linear Algebra, Calculus, and Basic Algebra and Trigonometry. I recommend creating separate folders for each of these categories and organize corresponding articles into these folders for ease of access and better organization.

**Comment by jamesjpk123** [comment]
I can start on a PR now.

**Comment by Bouncey** [comment]
Please hold off on this. I have a bunch of stubs to add to this section, I wouldn't want to undo all of the categorising work.

**Comment by jamesjpk123** [comment]
Ok

**Comment by chesun** [comment]
@Bouncey Do you mean stubs for the index.md for the entire mathematics section? Or new stubs for new folders on specific topics?

**Comment by nsuchy** [comment]
@Bouncey Did you ever to get adding the stubs?

**Comment by thecodingaviator** [comment]
@Bouncey , any progress on this?
