### ISSUE TITLE
Where to put article about markup languages?

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/guide#5959]
"Markup Language" is a term that comes up quite often but I can't find any explanation of what that is on the guide. I thought it could be good to make an article about it because that's not something that everybody obviously knows. However, I can't figure out where is the best place (the most relevant section) to put such an article... Any idea?

**Comment by Bouncey** [comment]
Are there a great many markup languages? Could it be considered a category of its own?

We already have an [article on markdown](https://guide.freecodecamp.org/developer-tools/markdown/). Would this be the best place for a singular article on markup?

**Comment by antoniolpaulos** [comment]
Could be under a subject like "Typesetting", also opening up a spot for TeX and LaTeX for example.

**Comment by jp-sauve** [comment]
Markdown (according to wikipedia) is a style of markdown. I'm all for the reorganization discussed in #414  in which I would take markdown out of the "Developer Tools" section, and group it with other markup languages. Then we can have TeX, groff, html,xml and any others together.

**Comment by thomaskuntzz** [comment]
@jp-sauve I fully agree with this. There are loads of markup languages, so let's make an article explaining the concept (it's talked about quite a lot accross the articles) and even maybe a full section for all the markup languages out there (like the ones you mentionen @jp-sauve).

**Comment by vikramnr** [comment]
@thomaskuntzz @Bouncey  Has anyone started this?

**Comment by thomaskuntzz** [comment]
No, it was just an idea, I'm not working on this

**Comment by vikramnr** [comment]
@Bouncey  So what is that we need to add in this article. Any languages in particular

**Comment by jp-sauve** [comment]
@vikramnr I think all mark-up languages should be included, but reorganization should wait until the bulk of the outstanding pull requests are dealt with. Trying to change structure now just makes existing submissions even more difficult to deal with, in my opinion.

**Comment by chrisgoodell** [comment]
I will take this up, given that it has been sitting for a while. I intend to enumerate several and provide abbreviated examples, but will go into full detail in explaining **Markdown** . It is probably most relevant and immediately useful for beginning web developers.

**Comment by Asjas** [comment]
@chrisgoodell Thank you 👍
