### ISSUE TITLE
Add AMP library and get this showing up with the AMP logo in Google search results

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide#65]

**Comment by Bouncey** [comment]
AMP requires an image in the article also, we should have a placeholder image for when there is no image available.

**Comment by QuincyLarson** [comment]
@Bouncey OK - sounds good. Let's use this for now

![banner](https://user-images.githubusercontent.com/985197/28370325-99914080-6c5f-11e7-8737-95c6ce268669.png)

**Comment by nsuchy** [comment]
You won't be able to use CSS Stylesheets (I.e. all CSS has to be inline and below 50kb), same applies to any Javascript. A lot of the application will have to be redesigned to be amp compatible. Thoughts?

**Comment by Bouncey** [comment]
Gatsby inlines our CSS in the `<head>`. If there is an issue with bootstrap, then we can look at the possibility of having an AMP and non-AMP version of the site. 

[More details](https://www.ampproject.org/docs/guides/discovery)

**Comment by nsuchy** [comment]
@Bouncey Bootstrap will be an issue - there will likely need to be two versions of the site for this to work.

**Comment by freebird1195** [comment]
Has anybody started working on the AMP version? I am up for it. Anyone wish to collaborate?

**Comment by QuincyLarson** [comment]
@freebird1195 We would welcome your help with this. To my knowledge, we haven't started implementing this yet. Would you like to tackle this?

**Comment by freebird1195** [comment]
@QuincyLarson I am willing to work on this. Would require some help getting started though.

**Comment by QuincyLarson** [comment]
@freebird1195 Sure - what help do you need? As far as I know, nobody here has experience with AMP, so I'm not sure how much help we could be, but we're definitely willing to try if you have specific questions :)

**Comment by freebird1195** [comment]
@QuincyLarson I just tried a small AMP project to learn. I will give it a shot, hope that it comes to be something useful. I will keep asking questions on the go. :)

**Comment by nsuchy** [comment]
@freebird1195 Yes the guides project uses React.

**Comment by QuincyLarson** [comment]
@freebird1195 Awesome - thanks! Have you had a chance to work on this any? Are you still interested in tackling this issue?

**Comment by freebird1195** [comment]
Hey, as much as I wanted to, I have never worked on React. I don’t think I will be able to dedicate that amount of time as of now, I am sorry.

**Comment by QuincyLarson** [comment]
@freebird1195 Thanks for letting us know. 

@Bouncey is this something you would be interested in implementing?

**Comment by johnkennedy9147** [comment]
@QuincyLarson @Bouncey @nsuchy What are the advantages? I don't know much about AMP but what I recall reading in articles was pretty negative - essentially good for Google, bad for everyone else.

**Comment by nsuchy** [comment]
@johnkennedy9147 AMP provides a very fast way to load articles on mobile, Google keeps it on their cache so it takes mere ms to load on mobile. Some people dislike saying it keeps people on Google longer, for freeCodeCamp though the goal isn't to make a profit but to provide knowledge to others. By using Google's AMP it makes it faster for people on the go to get knowledge. In our case it doesn't harm us and fully benefits the user above all else.
