### ISSUE TITLE
Add a gatsby plugin for relative links

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guide#693]
We need to catch relative links in markdown files to enhance UX.

Please add [this plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/) to our `gatsby-config.js` file and test

**Comment by Bouncey** [comment]
@systimotic I think we need more labels...

**Comment by systimotic** [comment]
@Bouncey 😄 I'm very tempted to add "enhancement", "on the roadmap", "bug" and "changes requested"

**Comment by ChrisMcNulty91** [comment]
@Bouncey Has anyone started looking at this? If not I'll get cracking

**Comment by systimotic** [comment]
@ChrisMcNulty91 You can go ahead!

**Comment by Ethan-Arrowood** [comment]
@ChrisMcNulty91 if you need help I can give you a hand 👍

**Comment by ChrisMcNulty91** [comment]
@systimotic @Bouncey I've added the plugin is there anything particular I can test to make sure it's working

**Comment by systimotic** [comment]
@ChrisMcNulty91 Nice work!

`src/pages/bootstrap/bootstrap-buttons/index.md` has a link at the end that is very close to a working relative link. Remove `/articles` from that link, run `yarn run dev` and make sure the page does not reload when you click that relative link.

If this is working, we can change some of the links that link to the full `https://guide.freecodecamp.org/...` path to relative link. There are at least 8 of these.

**Comment by ChrisMcNulty91** [comment]
@systimotic I'll get on that. So if I make the links to `https://guide.freecodecamp.org/... `Should they still open an new page or should it open in the same page

**Comment by Bouncey** [comment]
@ChrisMcNulty91 it should be as is you were clicking a link in the navigation
