### ISSUE TITLE
Pre-commit normalisation changes files

### ISSUE THREAD

**Issue by dhanushuUzumaki** [freeCodeCamp/guide#752]
While committing, the pre-commit script changes a lot existing, untouched files and leaves them unstaged.

<img width="1280" alt="screen shot 2017-10-06 at 9 16 49 pm" src="https://user-images.githubusercontent.com/14927280/31286416-b2007216-aadb-11e7-870d-48447048fa2a.png">

**Comment by Bouncey** [comment]
@dhanushuUzumaki thanks for raising an issue about this, believe it or not, this was intended behaviour,  it I don't think it is working out as I imagined. It just causes confusion. 

@systimotic Perhaps we should remove normalise from the pre-commit script and instead have a version of camperbot normalise every day and commit changes if necessary? My experiments with Travis doing it for every PR wouldn't have worked, Travis would have been throwing conflicts everywhere, editing the same files on multiple PRs.

**Comment by dhanushuUzumaki** [comment]
@Bouncey Thanks for letting me know. And once the discussion is complete, if possible I would like to give this a try.

**Comment by arcdev1** [comment]
@Bouncey... for contributors, do you want us to check-in these changes prior to submitting a PR?

**Comment by systimotic** [comment]
@Bouncey After https://github.com/freeCodeCamp/guides/pull/805, I'm fairly confident I could create a plugin that would remove the need for the link normalisation. 
The stub normalisation should only need to happen in certain cases. We could document this and make sure all reviewers are aware of when it needs to be run. 
The linter will already warn if a stub is missing, we'll need to document moving stubs and not being allowed to change stubs if you leave the "This is a stub" text.

**Comment by systimotic** [comment]
Update: I won't have be able to make time to create that plugin any time soon. It also turned out to be a lot more complicated than the other one 😅 I don't feel like I've explored all options yet, but I won't be able to do that soon. Feel free to move ahead as you consider appropriate.
