### ISSUE TITLE
Hexcodes article should be a section in CSS Colors page

### ISSUE THREAD

**Issue by jp-sauve** [freeCodeCamp/guide#7790]
Currently in https://guide.freecodecamp.org/computer-science/hexcode
This content belongs with the descriptions of rgb,rgba,hsl,hsla, and color names.
Adding empty section with #1839

**Comment by adiparab14** [comment]
@jp-sauve please review

**Comment by davcri** [comment]
Digital representation of colors it isn't specific to CSS, it's a more generic topic of digital images: evaluate carefully which is the best plate to describe this concepts.

**Comment by jp-sauve** [comment]
Fair point. All of the other methods, aside from CSS colour names, are also used outside CSS. I suggested it as the others are already in the CSS article, and ought to stay together, if not in their current location.
