### ISSUE TITLE
Add Electrical and Electronics Engineering

### ISSUE THREAD

**Issue by armgabrielyan** [freeCodeCamp/guide#7808]
Knowing about Electrical and Electronics Engineering is interesting even if you are software developer.

**Comment by johnkennedy9147** [comment]
@QuincyLarson out of scope for FCC guide?

**Comment by QuincyLarson** [comment]
@johnkennedy9147 @ArmenGabrielyan16 This is within the scope of our guide. @ArmenGabrielyan16 could you list out specific topics you'd like to see covered?

**Comment by ArmenGabrielyan16** [comment]
@QuincyLarson @johnkennedy9147

**Comment by QuincyLarson** [comment]
@ArmenGabrielyan16 Awesome. Those articles would be great. I think you should put "Electrical Engineering" as the root-level topic. Then could you nest all of those within topics and subtopics, then create stubs for them?

**Comment by ArmenGabrielyan16** [comment]
@QuincyLarson Thanks for your support. I think your suggestion is interesting. I am on it. I really appreciate any help from the community.

**Comment by QuincyLarson** [comment]
@ArmenGabrielyan16 Awesome! We're here to help if we can. Also, if you haven't already, jump into the gitter.im/freecodecamp/contributors room :)

**Comment by ArmenGabrielyan16** [comment]
@QuincyLarson Thank you very much.
