### ISSUE TITLE
Prioritize Concepts Encountered in freeCodeCamp Course

### ISSUE THREAD

**Issue by DamianRivas** [freeCodeCamp/guide#7823]
<h1>The Problem</h1>

Currently, the freeCodeCamp course contains external links for people to follow in order to better understand the concepts being introduced. For example, when you encounter hexadecimals for the first time in the course, it contains links to the Wikipedia pages for hexadecimals and the RGB color system:

![freecodecamp git](https://user-images.githubusercontent.com/10257813/32458096-3bac1c74-c2f9-11e7-8eee-b67ab74145cf.JPG)

This is a <b>huge</b> and obvious opportunity to increase traffic into the freeCodeCamp guides!

<h1>The Solution</h1>

We <b>must</b> prioritize the corresponding pages that are linked in the current freeCodeCamp course that way we can start linking to the guides instead. Again, this is a great opportunity to direct more people into the freeCodeCamp guides to increase traffic and hopefully get more people involved, and this is a quick way to add more value to freeCodeCamp in general! So, I'm not sure how github works yet, but if there's a way to give pages priority over others then we should consider the concepts introduced in the course so contributors can work on these pages first to implement them into the course asap, otherwise visitors will have nothing to read!

![image](https://user-images.githubusercontent.com/10257813/32457997-defc906c-c2f8-11e7-966d-8f600fec2a33.png)

---

> ✅️ By submitting this issue, I have verified the following

- ✅️[Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- ✅️[][Checked] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by johnkennedy9147** [comment]
@DamianRivas people are more likely to create content for an article if a stub already exists so if we can get a list of all the links to other sites in the course we can cross reference and create stubs for any that are missing. But as for pushing contributors toward fleshing out stubs or existing articles, everyone is a volunteer and only likely to write about what they know and are interested in. I definitely think the course material should include links to Guides wherever an article on the topic exist on guides but that would need to be changed in the course repo.
