### ISSUE TITLE
Articles imported from forum contain invalid nav links

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/guide#7825]
Looks like some articles which were imported from FCC Forum contain nav links that make no sense within guides.

No idea how many instances there would be.

Example:
![image](https://user-images.githubusercontent.com/26827682/32468409-0e190fcc-c346-11e7-8116-6f69cb1b8c2c.png)

Not sure if there is a quick way to identify affected articles, likewise if can be resolved any way other than manual editing.

thoughts?
---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by systimotic** [comment]
Good catch @johnkennedy9147! I looked into this before, and this was the only instance of this that I could find. Regardless, https://github.com/freeCodeCamp/guides/pull/739 will fix issues like this one where there are three or more links on a single line.
