### ISSUE TITLE
Implement schema.org 

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/guide#7832]
To aid our SEO, we should implement the [http://schema.org/TechArticle](http://schema.org/TechArticle) schema.

Follow the [getting started guide](http://schema.org/docs/gs.html).

The implementation should be programattic i.e. we shouldn't have to edit each article to get this working.

It would probably be easier to do this through a plugin that hooks into the `gatsby api`, specifically the `onCreateNode` hook. Checkout the plugin @systimotic wrote to apply the correct formatting to emoji's from the forum, [in the repo here](https://github.com/freeCodeCamp/guides/tree/master/plugins/gatsby-remark-fcc-forum-emoji)

**Comment by chotuaashiq** [comment]
@Bouncey  I would like to work on this issue. Can you give me some more details as of what is to be done so that I can complete the issue :) .

**Comment by nsuchy** [comment]
@chotuaashiq Are you still interested in helping with this issue?

**Comment by chotuaashiq** [comment]
@nsuchy @Bouncey I didn't get any clear insight of what is to be done. If you can explain it to me then I will surely do the issue
