### ISSUE TITLE
Create way to separate current from deprecated code

### ISSUE THREAD

**Issue by jp-sauve** [freeCodeCamp/guide#7863]
I think there ought to be a way to mark older code, so that users know that while they might come across it, it's no longer used. I'm thinking specifically of HTML4 tags like "bgcolor" that have been replaced.

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by chotuaashiq** [comment]
@jp-sauve can you please give more details of what is to be done in this issue. I want to work on this issue.

**Comment by ShinduHub** [comment]
https://www.google.de/search?q=html+mark+deprecated+code&oq=html+mark+deprecated+code&aqs=chrome..69i57.11077j0j7&client=ms-android-huawei&sourceid=chrome-mobile&ie=UTF-8
Google is your friend

**Comment by jp-sauve** [comment]
@ShinduHub I'm not sure which result you're pointing to. This is more of a design decision for site consistency. I haven't seen a way, using mark-up, to mark code in the guide as deprecated. I'm not looking to mark active code as deprecated.
