### ISSUE TITLE
Add Redis Articles

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guide#7878]
A set of articles on the Redis Datastore would be a nice addition to the freeCodeCamp Guide. Thoughts?

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by amandeepmittal** [comment]
I agree, a good introduction will be great use!

**Comment by aditya1994** [comment]
I can help regarding this. Let's create something?

**Comment by amandeepmittal** [comment]
@aditya1994 It is great you want to initiate. You can get started by creating an article then submitting a PR. I am sure we can get other contributors to collaborate from there if there is a need for that.

**Comment by aditya1994** [comment]
Okay cool. I'll write a basic one and will then submit a PR.

**Comment by silent-lad** [comment]
Is the issue still open?

**Comment by nsuchy** [comment]
@silent-lad It’s open for anyone to contribute a PR :)
