### ISSUE TITLE
Security: Add tails/Kali OS articles

### ISSUE THREAD

**Issue by username1001** [freeCodeCamp/guide#7978]
Not sure if this will go under the stub: sercurity tools. But perhaps these tools could use their own article(?)

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by prankshaw** [comment]
Create Kali linux.md issue#7978 #8056 issue solved
