### ISSUE TITLE
Search results vanish when search bar loses focus

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/guide#8045]
I noticed that the search results vanish when the search bar loses focus. Is it the expected behavior? I find it really annoying, and as a bonus is makes the search results impossible to inspect in the browser...

Why don't the search results stay there nicely when I click somewhere outside the search bar?

**Comment by pridemusvaire** [comment]
That's a valid point, I would want to click on other parts of the page and still see my search results.

**Comment by 321zeggy** [comment]
I think this is happening because of the [`handleBlur()`](https://github.com/freeCodeCamp/react-freecodecamp-search/blob/e94dcf46a19a652536cf709ccd88621ce72e24a4/src/FCCSearchBar.js#L81) method in the `react-freecodecamp-search` module.

**Comment by systimotic** [comment]
I agree, this is really annoying. I've been playing around with this a bit to see if I can get it to only clear when you browse to a different page, but it's quite difficult as Gatsby doesn't really allow interacting with react-router.
I'll play around with it a bit more, but if anybody else comes up with a fix in the meantime, feel free to create a PR!

**Comment by systimotic** [comment]
The search has been moved to https://search.freecodecamp.org/, so this is no longer relevant.
