### ISSUE TITLE
Search results: article title and excerpt still underlined when hovering only the breadcrumb

### ISSUE THREAD

**Issue by thomaskuntzz** [freeCodeCamp/guide#8046]
A breadcrumb has recently been added to the search results (#751). I noticed that when I hover the breadcrumb underneath an article title in the search result, everything is underlined, while I would expect only the breadcrumb to be underlined. That is, the article title and excerpt are underlined even when I'm only hovering the breadcrumb (see screenshot below and notice the position of the pointer).

But as each search result item is wrapped in one link, it'll be difficult to underline only the breadcrumb when I'm hovering it, since when hovering the breadcrumb I'm also hovering the wrapper link which leads to the article...

<img width="1280" alt="screen" src="https://user-images.githubusercontent.com/16361470/35687776-df60ee52-076f-11e8-90e9-240d4cbbc383.png">

**Comment by rdev0rigin** [comment]
Done https://github.com/freeCodeCamp/guides/issues/8066
