### ISSUE TITLE
Mixed indented and fenced code blocks

### ISSUE THREAD

**Issue by bdeshi** [freeCodeCamp/guide#8074]
Some code blocks have extra spaces before each line.

Examples of good codeblocks:
* https://guide.freecodecamp.org/javascript/async-messaging-with-rabbitmq-tortoise
* https://guide.freecodecamp.org/javascript/html-dom-innerhtml-property

Examples of not-so-good codeblocks:
* https://guide.freecodecamp.org/javascript/window-settimeout-method
* https://guide.freecodecamp.org/css/css-position

Maybe this is because these were originally written as indented code blocks, then further fenced with ` ``` `.

If nobody is working on this, I'll be happy to submit a PR fixing these.

❗️ I'm aware of this bug: #587, and I think adding proper syntax identifiers after the beginning ticks (` ```javascript ` etc) should be okay.

---
> ✅️ By submitting this issue, I have verified the following
- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by chotuaashiq** [comment]
@smsrkr I claim this issue

**Comment by smsrkr** [comment]
Thanks, but I listed those pages only as examples. there are _a lot_ of such mixed blocks throughout the guide.

BTW, I'm already working on it.

**Comment by jp-sauve** [comment]
@smsrkr I accepted #8075 which fixes the two pages you listed, but leave the issue open for the rest of the fixes. Are you still working on this?

**Comment by smsrkr** [comment]
yup. I'm just waiting for #8086 to be merged.

**Comment by smsrkr** [comment]
okay, I'm going to follow the advice on 8086 and submit _patches_ in _batches_ :grin: -- adding missing labels and removing extra indent, both at once.
should I close this as well?
