### ISSUE TITLE
Add verifying git commits article

### ISSUE THREAD

**Issue by palash25** [freeCodeCamp/guide#8110]
**How to verify git commits with gpg signature** would make a nice addition to the guides.

This could be a nice issue for beginners to dive into git and make their first open source contribution. 

I currently don't have time for this issue so I would like a newcomer to take this up. If this issue has no takers in a month or so then ping me and I will submit a PR :wink:

**Comment by JFernandes1** [comment]
Hello! I'm a beginner and would like to help with this issue.

**Comment by palash25** [comment]
@JFernandes1 https://blog.github.com/2016-04-05-gpg-signature-verification/
This might help. :smile:

**Comment by bkbu1024** [comment]
I am willing to take this up, can u give te PR

**Comment by Asjas** [comment]
@JFernandes1 You can take the issue.

**Comment by Omkar-Ajnadkar** [comment]
As no one has completed this issue, with PR  #8146. Please review it and suggest if any modifications.

**Comment by arunikayadav42** [comment]
is this issue still open.I would love to contribute :)

**Comment by xTrulyForsaken** [comment]
I would also like to help out.

**Comment by Asjas** [comment]
@arunikayadav42 and @xTrulyForsaken 

This issue has been resolved in PR #8146. Closing this issue.
