### ISSUE TITLE
'line-length' is not a valid CSS property in Typography > Legibility and Readability guide

### ISSUE THREAD

**Issue by thomas-j-moffett** [freeCodeCamp/guide#8111]
I was browsing the guide and happened to read this part of it: https://guide.freecodecamp.org/typography/legibility-and-readability

The issue is with the info in the **Line length** bullet...

> In CSS the property to control line length is ‘line-length’. Example : line-length: 50ch;

As far as I am aware, there is no `line-length` CSS property, and that information should not be in the guide.

I also double checked MDN in case I missed some cool new addition to the CSS spec, and there is no `line-length` property there. 
https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index

---

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by johnkennedy9147** [comment]
@thomas-j-moffett I agree, never seen that before and cannot find any reference to it either - would you like to edit the article to remove the reference?

**Comment by Uberche** [comment]
Can I do this? Trying to figure out how to help with open source and need something to use to figure out pull requests. :) Have the "guides" section forked, can see where it says that. Do I need to request to change something here first or just change it and then create a pull request with what I did? Can I link the pull request to the issue #?

**Comment by Asjas** [comment]
Hi @Uberche,

There are two ways of opening a PR.

First way is to directly edit the page on this repo. It will then give you the option at the bottom of the page to name your PR and to give a description of the changes you made. You can then reference this issue by typing in `fixes #8111`. 

Second way to open a PR is by closing this repo and making changes to your copy. You can either do this directly in the browser or you can clone it to your computer and use a IDE such as Atom or VS Code to make the changes. You will then commit and push those changes to your clone of the Repo. Once done you can open your Repo in Github which will allow you to open a PR to this Repo.

**Comment by azizanaiem** [comment]
Hey; 
This is related to a typography concept than css property. the accurate way to mention this, via controlling font css style and max width of container of the content, you can control the length of line to fit the needed content. 
resource: https://blog.prototypr.io/how-to-set-perfect-line-lengths-for-the-web-528f08f8b344

**Comment by johnkennedy9147** [comment]
@Uberche Hi, lets give @thomas-j-moffett another couple of days and if he doesnt raise a PR or comment that he would like to fix this then you can pick it up.
If you do it then make the change in your fork and then raise a pull request, mentioning the issue number #8111 in the commit message or comments. thanks
