### ISSUE TITLE
Change in View

### ISSUE THREAD

**Issue by BhaveshSGupta** [freeCodeCamp/guide#8113]
Currently Scroll bar is there on right had side when the content is smaller then the window.
Because of the property overflow-y:scroll property given to content div.
![image](https://user-images.githubusercontent.com/4209637/38077550-f2b93726-3356-11e8-891a-aefd51708134.png)

Instead if overflow-y:auto is given then scroll bar will appear when content is long.
It is a small css change if required I can fix this issue.

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Bouncey** [comment]
Closed via #8116
