### ISSUE TITLE
Missing favicon images

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guide#8123]
While preparing another issue related to favicons and adblockers (will be added soon), I noticed that some of the favicons are missing from the current AWS S3 bucket. These images should either be added to the S3 bucket or we need to remove them from meta to avoid unnecessary HTTP requests.

**List of missing favicon images**
- https://s3.amazonaws.com/freecodecamp/favicons/mstile-150x150.png
- https://s3.amazonaws.com/freecodecamp/favicons/mstile-310x150.png
- https://s3.amazonaws.com/freecodecamp/favicons/mstile-310x310.png
- https://s3.amazonaws.com/freecodecamp/favicons/apple-touch-icon-144x144.png
- https://s3.amazonaws.com/freecodecamp/favicons/apple-touch-icon-72x72.png
- https://s3.amazonaws.com/freecodecamp/favicons/apple-touch-icon.png
- https://s3.amazonaws.com/freecodecamp/favicons/apple-touch-icon-precomposed.png
- https://s3.amazonaws.com/freecodecamp/favicons/android-chrome-96x96.png
- https://s3.amazonaws.com/freecodecamp/favicons/android-chrome-48x48.png
- https://s3.amazonaws.com/freecodecamp/favicons/android-chrome-36x36.png

**Comment by jdk1997** [comment]
Hi! Can I work on this issue?

**Comment by diazabdulm** [comment]
@jdk1997 Just create a pull request, if I'm not mistaken.

**Comment by JimmayVV** [comment]
is this still an issue? I don't believe I see the problem url's as described above in meta.js as I would have expected, and I don't see any explicit calls to them either in the repo.

Not sure if something else removed those icons from meta?

**Comment by nsuchy** [comment]
@JimmayVV I'll double check the commit history and let you know.
