### ISSUE TITLE
CREATING A PULL REQUEST

### ISSUE THREAD

**Issue by ASrima** [freeCodeCamp/guide#8125]
I am trying to clone the repository on my computer but it keeps saying permission denied and then again tried to add the remote repository but it does not allow me to push the commit

---

![screen shot 2018-04-08 at 4 20 39 pm](https://user-images.githubusercontent.com/26333574/38472112-f774aa62-3b48-11e8-9cab-4ccda0363844.png)

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Bouncey** [comment]
Hi @ASrima Be sure you are pushing to your fork of the guide and not freeCodeCamp/guides

`git remote -v` should tell you were your `origin` is pointing, it should be something like 

```sh
$ git remote -v
origin	https://github.com/ASrima/guides.git (fetch)
origin	https://github.com/ASrima/guides.git (push)
```

**Comment by ASrima** [comment]
Hi @Bouncey I tried doing that too but it didn't work. 
![screen shot 2018-04-08 at 7 14 28 pm](https://user-images.githubusercontent.com/26333574/38521079-99c1f526-3c12-11e8-9066-37c137e8f430.png)

**Comment by Asjas** [comment]
Hi @Asrima

Have you made any progress on cloning the project locally? :smile:

Can we close this issue?

**Comment by ASrima** [comment]
Hi @Asjas
Yes I was able to clone it on my desktop thank you for all the help @Bouncey. The github public key messed up my Gitlab key as I cloned both on my desktop and it created an issue but my professor helped me solve the problem so it's all good now.

**Comment by Asjas** [comment]
@ASrima Great! I'm glad you got it working.
