### ISSUE TITLE
Better codeblock syntax recommendation in Style Guide

### ISSUE THREAD

**Issue by smsrkr** [freeCodeCamp/guide#8152]
In order to avoid #587 in new articles, the style guide can more prominently point out that codeblocks should always be in fenced style (as opposed to plain indented) and must have a syntax label, generic ones like ` ```text` where no proper labels are appropriate.
<sup>(from #8132)</sup>

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by nsuchy** [comment]
I support this change 👍

**Comment by alinepegas** [comment]
I agree

**Comment by smsrkr** [comment]
I'm not awesome at articulating; how does ^that^ PR read?
