### ISSUE TITLE
Add Angular Articles

### ISSUE THREAD

**Issue by sosmaniac-FCC** [freeCodeCamp/guide#8158]
Hello! I noticed the Angular section of the guide was lacking content. I have been reading and practicing Angular 6 for the last week and a half, so I believe I can do something about that. I propose the following topics to explain (might not be able to get to them all):

* CLI and Filesystem (Basic commands to generate/interpret an app)
* Data Binding (How components interact)
* Pipes (Inline output transformation)
* Directives (Structural and Attribute)
* Services (Separating out http, logging, etc)
* Template HTML
* Encapsulated CSS (Shadow DOM)
* Components
* Modules
* Lifecycle Hooks
* Elements and the DOM
* Angular Decorators (Metadata)
* Dependency Injection
* Views & Templates (Embedded and Host)
* Basic Animations
* Basic Routing
* Basic Testing

Honestly, the Official Angular documentation is very good. My goal is to sell the idea of each concept in a basic, fundamental way before linking to the most relevant part of the official docs for readers to learn more. I may include links to other sources as per necessary. If anyone wants to help me tackle this endeavor, that would be super swell! Otherwise, please let me know if this all sounds OK for the guide!

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by amandeepmittal** [comment]
I agree with you. I think Angular section needs to have more articles.

**Comment by pertrai1** [comment]
@sosmaniac-FCC the Angular index.md file has content in it but the page shows as a stub for me. Do you see the same?

**Comment by sosmaniac-FCC** [comment]
@pertrai1 Would not be a difficult process since the section lacks content. It is just a matter of approval. The current content is mostly AngularJS, so renaming the section to AngularJS and removing any content pertaining to Angular ought to do the trick.

**Comment by sosmaniac-FCC** [comment]
@amandeepmittal Thanks for merging my articles. I really appreciate it. Unfortunately, my next project came on a bit quicker than I had anticipated.

I managed to cover almost all of the article topics I listed. The only thing completely missing is testing. I should have time to finish this up later (~month from now). For now, I am closing the issue.

I did do some research, but there was just not enough time to follow through. Here is the outline I came up with:

# Unit Testing
#### Motivation
#### Unit Testing in Angular
#### Jasmine, Protractor, and Karma
#### Testing Services
#### Testing Components
#### Testing Pipes
#### Testing Directives
#### Conclusion

Again, I will be back later once there is more time. If anyone else wants to write about testing in the meantime, feel free to reopen the issue.

**Comment by amandeepmittal** [comment]
@sosmaniac-FCC Thank you so much for your effort! 👍
