### ISSUE TITLE
Having two pages on `npm` necessary?

### ISSUE THREAD

**Issue by amandeepmittal** [freeCodeCamp/guide#8161]
There are currently two pages on `npm`. One in developer tools ([here](https://guide.freecodecamp.org/developer-tools/npm)) and other under Node.js section ([here](https://guide.freecodecamp.org/nodejs/npm)) for which I have recently submitted a PR #8160.

All I am saying is that IMO there is no need of having two separate pages for `npm`. If, however, under any circumstance, there is a need to for content on npm under developer tools, it should be redirect to  the one under Node.js section.

Another scenario we can have is to remove the npm from Node.js and put the content under develop tools completely. If that is the most appropriate solution everybody think is.

---

> ✅️ By submitting this issue, I have verified the following

- [X] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [X] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by sosmaniac-FCC** [comment]
It think its OK to have npm listed twice under separate categories. I agree with you that having two different pages with similar information regarding npm is excessive. One ought to redirect to the other as you have suggested. Just my 0.02 cents!

**Comment by amandeepmittal** [comment]
Which one should redirect which one?

**Comment by ayushpratap** [comment]
In my opinion the page in Node.js should redirect to developer tools.

**Comment by amandeepmittal** [comment]
@ayushpratap Yes you can take this issue.

**Comment by ayushpratap** [comment]
Okay, I will try to submit a PR by tomorrow end of the day.

**Comment by amandeepmittal** [comment]
@ayushpratap did you submit the PR?

**Comment by Nirajn2311** [comment]
Is anyone doing this as I can do a PR at the moment.

**Comment by Asjas** [comment]
@Nirajn2311 Yeah I can't see a PR for this. If you want you can create one.

**Comment by SubhrajyotiSen** [comment]
@sarahshrivastava Maybe you can take this up!

**Comment by scottzoo** [comment]
Hi everyone - I took a look at this issue and I believe I can fix it.  It would be my first issue, pretty exciting!
From the look of the links, the [nodejs page](https://guide.freecodecamp.org/nodejs/npm) has a ton of good information:  .  [Dev tools page](https://guide.freecodecamp.org/developer-tools/npm)   has some good info and links too so another part of this might be to combine to a single npm page?

What do you think?  Let me know (if I need permissions, etc) and I'll have both nav links reference the best npm page (and can combine if that sounds good).

**Comment by amandeepmittal** [comment]
Hi, @scottzoo yes go ahead with merging the two pages and the redirecting one to another. When you submit a PR, let me know. 👍

**Comment by scottzoo** [comment]
@amandeepmittal  - great - I'll let you know when I submit the PR

**Comment by gayansanjeewa** [comment]
Hello @scottzoo how's the progress :)

**Comment by gowrimanoharir** [comment]
Hi, if this is still open I would like to work on this.

**Comment by amandeepmittal** [comment]
@gowrimamoharir yes it is still open.

**Comment by gowrimanoharir** [comment]
@amandeepmittal thanks will work on it

**Comment by gowrimanoharir** [comment]
Created the pr with required changes, also there was yarn content in npm file which I moved to yarn file and added redirect links between yarn and npm

**Comment by scottzoo** [comment]
Thanks @gowrimanoharir !  I got super busy with work and missed this.  I appreciate you picking it up.

**Comment by gowrimanoharir** [comment]
@scottzoo the existing content I moved from node folder seems to have issue (this article was flagged as plagiarism from https://www.sitepoint.com/beginners-guide-node-package-manager/) so my pr is for combining content is closed. I might not be able get back to this till this weekend. so if you want to give it a shot pls go ahead. Thanks.
