### ISSUE TITLE
TypeScript Interface

### ISSUE THREAD

**Issue by pertrai1** [freeCodeCamp/guide#8163]
Would be nice to have a section in TypeScript to detail and explain interfaces. You can assign to me if this is something that would be good to add.

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Hi @pertrai1 

That is a good idea. I am assigning you to it :+1:.

**Comment by pertrai1** [comment]
@Asjas I am a little confused. I see a directory under TS from the latest master for interfaces, but I do not see it being displayed in the guide?
