### ISSUE TITLE
Broken image link: /mathematics/hexagon

### ISSUE THREAD

**Issue by luandy64** [freeCodeCamp/guide#8171]
The very last image needs to be changed. It currently says "Discover pixelbay free images No Hotlinking".

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by domwakeling** [comment]
Fixed in PR #8183, although it won't appear on the live site immediately.
