### ISSUE TITLE
Translate README.md to Brazilian Portuguese

### ISSUE THREAD

**Issue by lupuselit** [freeCodeCamp/guide#8175]
I will be translating the readme.md to Brazilian Portuguese

---

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by thecodingaviator** [comment]
I thin that this issue has served it's purpose, it can be closed. If any further discussion is required, I think we should use this thread - #310 .
