### ISSUE TITLE
Autoupdate Broken + Slow page load times on yarn dev after a page reload on Windows 10

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/guide#8197]
After editing an article's content and saving the changes. The content in the browser does not automatically update and a refresh of the page takes about 1 minute. This makes content writing difficult.

**Steps to reproduce issue:**
1) Install Nodejs 8.11.2 with Chocolately on Windows 10 Pro
2) Install Yarn and any other dependencies you may need (for example Python and windows-build-tools)
3) Run the guide platform with `yarn run dev` in Powershell.
4) Open an article in Chrome
5) Made an edit to the article that's open in Chrome
6) See that the article does not automatically update and trying to refresh the page takes up to a minute

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by nsuchy** [comment]
@Bouncey You seem more involved with platform issues - can you take a look at this? Thanks 😄

**Comment by Bouncey** [comment]
@nsuchy is this still an issue?

**Comment by nsuchy** [comment]
@Bouncey Hurricane Florence has impacted me and will not have home internet until tomorrow after repairs are complete. I'll investigate and post an update to this issue. Thanks for your patience :|
