### ISSUE TITLE
freeCodeCamp logo should redirect to www.freecodecamp.org

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guide#8201]
Currently clicking the freeCodeCamp logo in the navbar leads back to guide.freecodecamp.org

We want this action to be consistent across all of freeCodeCamp. 

![freecodecamp_guide](https://user-images.githubusercontent.com/985197/41430903-ed351394-6fd6-11e8-8dae-12b79a357f5b.png)

**Comment by Nirajn2311** [comment]
Will work on it.
