### ISSUE TITLE
Consolidate media-query pages

### ISSUE THREAD

**Issue by domwakeling** [freeCodeCamp/guide#8203]
Propose that the media-query guides be consolidated as follows:
* edit content of `src/pages/css/media-queries` into `src/pages/css/css3-media-queries`
* delete `src/pages/css/media-queries`
* delete `src/pages/css/css3-at-media-rule` (a stub) 

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Navneet-Sahota** [comment]
Hey @domwakeling, I would like to work on this.

**Comment by richsalvucci** [comment]
@domwakeling I added in the additional links that I thought were useful I will close PR https://github.com/freeCodeCamp/guide/pull/7357.

**Comment by domwakeling** [comment]
@richsalvucci just merged your new PR, thanks for looking at this :+1:

**Comment by nischaldutt** [comment]
I would like to work on this.

**Comment by Nirajn2311** [comment]
@domwakeling could you close the issue if it is solved.
