### ISSUE TITLE
Bug: Certficates > Missing Letters, inermediate solution

### ISSUE THREAD

**Issue by FrancoB411** [freeCodeCamp/guide#8205]
[Missing Letters JS Algorithm, intermediate solution](https://forum.freecodecamp.org/t/freecodecamp-algorithm-challenge-guide-missing-letters/16023) in the forums and the guides has a bug.

It cannot handle sequential missing letters, so if you had an input of 'abcf', it would only return 'd' instead of 'de'.

I tried to add a comment in [the forum](https://forum.freecodecamp.org/t/freecodecamp-algorithm-challenge-guide-missing-letters/16023) but it was locked, so I posted an issue on [freeCodeCamp repo](https://github.com/freeCodeCamp/freeCodeCamp/issues/17604#issuecomment-397865566), and they pointed me here. 

Here's a working solution that uses `reduce` instead of `map`

```javascript
function fearNotLetter(str) {
    const toMissingLetters = (missingLetters, ch, index) => {
        if(index == 0) return missingLetters;
        
        const charCode = ch.charCodeAt();
        const prevCharCode = str.charCodeAt(index - 1);
        let nextExpectedCharCode = prevCharCode + 1;

        while(nextExpectedCharCode != charCode) {
            const nextMissingLetter = String.fromCharCode(nextExpectedCharCode);
            missingLetters = missingLetters.concat(nextMissingLetter);
            nextExpectedCharCode += 1;
        }
        return missingLetters;
    };

    return str.split("").reduce(toMissingLetters, '') || undefined;
};

fearNotLetter("abcf");
```
I can make a PR for the guides repo if you guys want, but it would be a good idea to change the forum, which is what the lessons links led me to, and what other people are probably seeing first, like I did. 

Thoughts?

Thanks!

**Comment by Asjas** [comment]
Hi @FrancoB411 

You can open a PR to fix the solution code in the `Guide Repo`. All solutions will be linked to the `Guide Repo` and not the forum in the future. So updating the forum isn't needed. The forum is also not under the management of the `guide` team.
