### ISSUE TITLE
back ground inoperative, due misspeel "background-color" to "backgroud-color"

### ISSUE THREAD

**Issue by shouhui** [freeCodeCamp/guide#8225]
Insert description of issue here

---

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Closing due to no response from @shouhui.
