### ISSUE TITLE
Add guidelines for documenting code 

### ISSUE THREAD

**Issue by viniciusarre** [freeCodeCamp/guide#8245]
Insert description of issue here

---

Hello!

This is a request for a detailed how to document your own code guide. I have been thinking about it having some best practices when it comes to documentation, how one can get started on documenting their own code. 

It should have examples and details on how to document, guidelines to fulfilling requirements through user's stories and a tips on keeping it clean. 

Cheers!

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by RyanPisuena** [comment]
Hey guys attempting to create a new folder for you all!

**Comment by Asjas** [comment]
Merged PR #8376 that created a `stub` for [Code Documentation](https://github.com/freeCodeCamp/guide/tree/master/src/pages/documentation). 

Closing this issue.
