### ISSUE TITLE
[BUG] Applied Visual Design, background pattern

### ISSUE THREAD

**Issue by nickmansrob** [freeCodeCamp/guide#8248]
The right solution isn't accepted. Code:
`<style>
  body {
    background: url(https://i.imgur.com/MJAkxbh.png);
  }
</style>`

The preview shows the image correctly.

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Hi @nickmansrob. 

This is the freeCodeCamp Guide repository. Which is the guide documentation repository.

Please open a issue on the [freeCodeCamp repository](https://github.com/freeCodeCamp/freeCodeCamp/issues/new). That is the correct repository to open the issue. No-one here will be able to assist you.

**Comment by littleaggieiscoding** [comment]
Hi @nickmansrob,

have you opened an issue regarding the problem described?

I can't find it in issues, and it seems the problem still exists (although the code is correct- it's not accepted).

**Comment by Asjas** [comment]
@littleaggieiscoding 

Can you please explain where this issue exists? You are on the guide repository. 

I would suggest opening a issue on the actual freeCodeCamp repo and not this guide repo.

**Comment by littleaggieiscoding** [comment]
Hi @Asjas ,

Already checked the actual freecodecamp repo and found the answer (@nickmansrob opened the issue).
Sorry for troubles 🙂
