### ISSUE TITLE
Basic CSS: Use Attribute Selectors to Style Elements

### ISSUE THREAD

**Issue by aoulouz** [freeCodeCamp/guide#8258]
Insert description of issue here

---

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Hi @aoulouz 

This is the Guide Repository. Please open a issue on the [freeCodeCamp Repository](https://github.com/freeCodeCamp/freeCodeCamp/issues/new) as we do not have any challenges on this repository.
