### ISSUE TITLE
Basic CSS: Use Attribute Selectors to Style Elements

### ISSUE THREAD

**Issue by aoulouz** [freeCodeCamp/guide#8259]
Insert description of issue here

-please help me with this thanks.--

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️
![screenshot 16](https://user-images.githubusercontent.com/24766849/42603947-0e43614a-853e-11e8-9eb7-edc8feeac9b0.png)

**Comment by sabaeky** [comment]
hi :)
if you use
`[type='checkbox'] {
  margin: 10px 0px 15px 0px;  
  }`
in your style,the code will run correctly.

**Comment by Asjas** [comment]
Hi @aoulouz 

This is the Guide Repository. Please open a issue on the [freeCodeCamp Repository](https://github.com/freeCodeCamp/freeCodeCamp/issues/new) as we do not have any challenges on this repository.
