### ISSUE TITLE
Applied Visual Design: Adjust the Height  challenge

### ISSUE THREAD

**Issue by Ahmed-Elbessfy** [freeCodeCamp/guide#8277]
Insert description of issue here

---

> ✅️ By submitting this issue, I have verified the following
In the Adjust Height of the Element using height property, the h4 tag after my solution is like this:

```
 h4 {
    text-align: center;
    height: 25px;
  }

```

but still doesn't pass the challenge and asks for changing the height of h4 to be 25px value. Also, I have inpected the elelment properties and its height was equal to 25px. 

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Hi @Ahmed-Elbessfy 

This is the Guide Repository. Please open a issue on the [freeCodeCamp Repository](https://github.com/freeCodeCamp/freeCodeCamp/issues/new) as we do not have any challenges on this repository.
