### ISSUE TITLE
Error causing test to fail - Create a Horizontal Line Using <hr> tag

### ISSUE THREAD

**Issue by myDeveloperJourney** [freeCodeCamp/guide#8322]
I've attempted solving this exercise several times. There are two possible issues:

- **A** I'm not understanding the question.
- **B** There's an error preventing the test to pass

I checked the console and saw there were errors as well. 

I've attached photos as well. I hope this helps. 

Thank you!
<img width="1674" alt="screen shot 2018-07-29 at 1 36 32 pm" src="https://user-images.githubusercontent.com/20377140/43369084-9a74fe3a-9335-11e8-83aa-9f41d6515d2f.png">
<img width="1672" alt="screen shot 2018-07-29 at 1 39 33 pm" src="https://user-images.githubusercontent.com/20377140/43369085-9a83bd30-9335-11e8-8cf5-9cec214c68f9.png">
<img width="1673" alt="screen shot 2018-07-29 at 1 41 11 pm" src="https://user-images.githubusercontent.com/20377140/43369086-9a95a4fa-9335-11e8-89c9-0597b87ef7c2.png">

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by oieusouamiguel** [comment]
This error is happening to me too. I tried to copy the code from the next lesson, but this error this goes on. 
![image](https://user-images.githubusercontent.com/20358128/43372063-f7a310fa-9372-11e8-8a8c-024d39102952.png)

**Comment by myDeveloperJourney** [comment]
Thanks for adding this @oieusouamiguel! At least I know I’m not crazy over here ha! Well hopefully we can get this sorted out soon.

**Comment by Asjas** [comment]
Hi @myDeveloperJourney 

This is the freeCodeCamp Guide repo you are currently on.

I would suggest opening a issue on the [Curriculum](https://github.com/freeCodeCamp/curriculum) or [Learn](https://github.com/freeCodeCamp/learn/issues) repo.
