### ISSUE TITLE
Incorrect file in C++ Tokens Variables folder

### ISSUE THREAD

**Issue by Asjas** [freeCodeCamp/guide#8334]
There are currently 2 files in the [C++ Tokens Variables](https://github.com/freeCodeCamp/guide/blob/master/src/pages/cplusplus/tokens-variables) folder. There can only be one file per folder and it needs to be called `index.md`. This is breaking the folder and it's not displaying correctly in the guide.

What needs to happen is that the file `static variable info` needs to be broken out into its own folder and it needs to be renamed to `index.md`.

Marking this as `help wanted`. Anyone is free to pick this up and fix it. Please read the [Contributing Guide](https://github.com/freeCodeCamp/guide/blob/master/CONTRIBUTING.md#article-style-guide) to see the Article Style Guide.

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by seely1991** [comment]
I'd like to try this one if I could.

**Comment by Asjas** [comment]
Closed in PR 8335
