### ISSUE TITLE
All Netlify deployments are failing

### ISSUE THREAD

**Issue by Asjas** [freeCodeCamp/guide#8355]
The Netlify deployments are currently all failing. I don't know if it's because we are currently at 4161 pages in the repo and Linux has a default `ulimit` of 4096. I had to push my `ulimit` to 10000 on my local machine to get it building locally.

This is an example of the [Netlify Deploy error](https://app.netlify.com/sites/guide/deploys/5b6b3481dd28ef41e9eee0aa).
```
8:20:50 PM: Build ready to start
8:20:51 PM: build-image version: 7c49b266ed8abd833dee6036ec0a4b9ee887658a
8:20:51 PM: buildbot version: f58df58ab0bceffdcb8d1e60fec992495a2a6751
8:20:51 PM: Fetching cached dependencies
8:20:51 PM: Starting to download cache of 892.2MB
8:20:55 PM: Finished downloading cache in 3.646708876s
8:20:55 PM: Starting to extract cache
8:21:08 PM: Finished extracting cache in 12.686600452s
8:21:08 PM: Finished fetching cache in 16.543513879s
8:21:08 PM: Starting to prepare the repo for build
8:21:09 PM: Preparing Git Reference refs/heads/master
8:21:11 PM: Failing build: Failed to prepare repo
8:21:11 PM: failed during stage 'preparing repo': exit status 1
8:21:11 PM: Finished processing build request in 20.121881764s
```

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by jsjoeio** [comment]
Didn't you just say this should be fixed in #8354?

**Comment by Asjas** [comment]
That PR was to fix the error in that [specific](https://app.netlify.com/sites/guide/deploys/5b686b4cb13fb1215fa569a1) Netlify deploy. That problem was a file called something other than `index.md` being in a folder. I though fixing that would fix the Netlify builds but it was not related to the main problem.

`Error: ENOTDIR: not a directory, scandir '/opt/build/repo/src/pages/cplusplus/ Conditional_operator.md'`

This seems to be a problem with all builds, new and previous, where it's failing to prepare the repo according to Netlify.

`Failing build: Failed to prepare repo`

I've been searching on the internet to see why Netlify would give such an error message.

**Comment by raisedadead** [comment]
And now I checked there is a new error on the build similar to the one that you may have fixed:
https://app.netlify.com/sites/guide/deploys/5b6b5453fdd72a569d274fa6

/cc @Bouncey

**Comment by raisedadead** [comment]
@Bouncey is adding tests that will fail the CI to avoid this. And we could then fix all naming issues in a go.

**Comment by Asjas** [comment]
@Bouncey Ah, Okay I see. Thanks :+1:
