### ISSUE TITLE
help wanted- how can I put red-class in stylesheet?

### ISSUE THREAD

**Issue by dipsikharay** [freeCodeCamp/guide#8357]
Insert description of issue here

---

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

<style>
   
   h2.red-text{
    color: red ;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

how Can I attach red-class in stylesheet?

**Comment by alambeaux** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/issues/10212

**Comment by Asjas** [comment]
@dipsikharay This is the wrong repo for reporting issues with the freeCodeCamp curriculum. This is the freeCodeCamp guide repo
