### ISSUE TITLE
Move "Amazon Web Services" directory under "Cloud Development" and start AWS articles there

### ISSUE THREAD

**Issue by Leoat12** [freeCodeCamp/guide#8364]
I was taking a look at the guide repository and it looked awesome. I would like to contribute with that. I notice that Amazon Web Services had only a stub in its directory, but it has an article in the Cloud Development directory. So it wouldn't be better to put the Amazon Web Services directory under Cloud Development and start articles about AWS services there? 

I would be glad to do that and start write an article right away, but just to make sure if this structure change makes sense. Thank you! :)

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
@Leoat12 

I would suggest removing the stub and folder for [AWS](https://github.com/freeCodeCamp/guide/tree/master/src/pages/aws). There is already a [Amazon AWS](https://github.com/freeCodeCamp/guide/tree/master/src/pages/cloud-development/amazon-aws) folder in Cloud Development that can be used.

You can open a PR to remove the duplicate folder.
