### ISSUE TITLE
[Cloud Development] 2 articles about Google Cloud Platform

### ISSUE THREAD

**Issue by a7mam7ma** [freeCodeCamp/guide#8380]
In cloud development there are 2 articles with the title 'Google Cloud Platform' one of them is the updated version of the other. 

[article 1](https://guide.freecodecamp.org/cloud-development/gcp)
[article 1 Updated](https://guide.freecodecamp.org/cloud-development/google-cloud)
---

- [✅️] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️

**Comment by amandeepmittal** [comment]
@a7mam7ma You can submit a PR to delete the older one.

**Comment by nsuchy** [comment]
@amandeepmittal Generally you'd need to merge content from the article you wish to delete, into the article which will take over.

**Comment by amandeepmittal** [comment]
@nsuchy The content in both the articles is overlapping ATM. It's a duplicate. I get your point. I should have mentioned which article to remove and which to keep. Apologies for that. 🙏

@a7mam7ma please remove [this article](https://guide.freecodecamp.org/cloud-development/gcp) in the PR you submit.
