### ISSUE TITLE
Sass Challenge doesn't work

### ISSUE THREAD

**Issue by Waffun** [freeCodeCamp/guide#8404]
### URL
[https://learn.freecodecamp.org/front-end-libraries/sass/split-your-styles-into-smaller-chunks-with-partials]

### Instructions
Write an @import statement to import a partial named _variables.scss into the main.scss file.

### Code Editor
// The main.scss file
@import 'variables.scss' //Tried with 'variables.scss'; - "variables.scss" - "variables.scss";

### Output
// running test
Your code should use the @import directive, and should not include the underscore in the file name.
// tests completed

**Comment by loganripplinger** [comment]
I also ran into a similar problem while working through this problem. I am working on updating the text and splitting the test into multiple tests for the sake of clarity.
