### ISSUE TITLE
Add Window's Command Prompt Article to the Terminal/Command Prompt Section  

### ISSUE THREAD

**Issue by AndrewZamora** [freeCodeCamp/guide#8411]
I would like to add a Window's Command Prompt article to the Terminal/Command Prompt Section if that is okay. I've looked through raised issues and pull requests. I don't think anyone is working on that. I'm pretty new to Git and Github so if I'm mistaken I apologize in advance.  

---

> ✅️ By submitting this issue, I have verified the following

- [] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by joshalling** [comment]
@AndrewZamora I think this would be a welcome addition to the guide. I am looking forward to seeing what you come up with. :+1:

**Comment by AndrewZamora** [comment]
@joshalling  I've finished the article and used `git add .` to stage my changes. But when I try to commit with `$ git commit -m "Added windows-command-prompt directory to the terminal-commandline directory and added windows-command-prompt article to index.md"` . I get this in my command line:
```
"Running pre-commit script. This can take a while."
'plugins)' is not recognized as an internal or external command,
operable program or batch file.
pre-commit:
pre-commit: We've failed to pass the specified git pre-commit hooks as the `format`pre-commit: hook returned an exit code (255). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:pre-commit:
pre-commit:   git commit -n (or --no-verify)pre-commit:
pre-commit: This is ill-advised since the commit is broken.
pre-commit:
```
I made an index.md file in the new directory I added so I'm not sure why I can't make a commit. Am I using the wrong git commit command?
![image](https://user-images.githubusercontent.com/31365406/44615840-870e3100-a87e-11e8-910e-ffa308053a05.png)

**Comment by joshalling** [comment]
@AndrewZamora It looks like something may be corrupted in your local repo. The odd thing is that I don't think the guide even has a pre-commit hook. Maybe try cloning a fresh copy of the repo, and see if that works.
