### ISSUE TITLE
Duplicate page: else if statement in C++ 

### ISSUE THREAD

**Issue by joshalling** [freeCodeCamp/guide#8432]
There are two pages in the C++ section with essentially the same info: _If-Else Statement_ and else __if statement__. These stubs should be merged.

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Mystigan** [comment]
Hello,
I have opened PR #8458 to address this issue.
Please review it and let me know if is okay or if something more is to be done.
PS: First contribution. Please do correct me if I did something wrong.
