### ISSUE TITLE
Use Attribute Selectors to Style Elements

### ISSUE THREAD

**Issue by zavier01** [freeCodeCamp/guide#8433]
Insert description of issue here

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
@zavier01 What is the issue here? You don't have a description in the issue.
