### ISSUE TITLE
Responsive Web Design Principles: Create a Media Query

### ISSUE THREAD

**Issue by tangyao42120836** [freeCodeCamp/guide#8627]
Insert description of issue here
I think my answer is right.but there is a mistake tip all the time.help someone can help me 
<style>
  p {
    font-size: 20px;
  }
  
  /* Add media query below */
  @media (max-height: 800px) {        
     p {
       font-size: 10px; 
    }
  }

</style>
  
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tempus massa. Aenean erat nisl, gravida vel vestibulum cursus, interdum sit amet lectus. Sed sit amet quam nibh. Suspendisse quis tincidunt nulla. In hac habitasse platea dictumst. Ut sit amet pretium nisl. Vivamus vel mi sem. Aenean sit amet consectetur sem. Suspendisse pretium, purus et gravida consequat, nunc ligula ultricies diam, at aliquet velit libero a dui.</p>

**Comment by Asjas** [comment]
Hi @tangyao42120836. 

Please note this is the freeCodeCamp guide repo. Please use our freeCodeCamp [Gitter helproom](https://gitter.im/FreeCodeCamp/HelpFrontEnd) for asking for help.
