### ISSUE TITLE
[Guides] Permanent "expand it" link on existing guide pages

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/guide#8649]
I've seen a link on every stub page for campers to add guides;

![vivaldi_2018-09-21_12-48-57](https://user-images.githubusercontent.com/12052430/45877166-3c100c80-bd9d-11e8-939b-17cc9fc6081a.png)
and I wonder if we should maintain that (like adding a "mini-footer") on existing ones so we all have easy access to them again if we want to add more content, fixes, etc.

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by hiparthparth** [comment]
I think rather than doing that, we should dedicate an extra page where there is a search bar with the links of all other guides that have been edited. Contributors can keep adding to that list after they write a guide for a tutorial
