### ISSUE TITLE
[Guides Python] Combain related pages

### ISSUE THREAD

**Issue by Felix-Raj** [freeCodeCamp/guide#8654]
It will be better if pages relating to same subject/content is merged into one. For example there are multiple pages discussing about python string operations/methods, why not merge them into a single page, may be under a directory named python-strings or so.

> ✅️ By submitting this issue, I have verified the following

- [ x ] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ x  ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Skyth3r** [comment]
What pages are you seeing that are like this?

Would you mind just linking them here, please?

**Comment by Felix-Raj** [comment]
The following are related to list in python-
* https://guide.freecodecamp.org/python/list-append-method
* https://guide.freecodecamp.org/python/list-extend-method
* https://guide.freecodecamp.org/python/list-comprehension
* https://guide.freecodecamp.org/python/list-index-method
* https://guide.freecodecamp.org/python/list-remove-method
* https://guide.freecodecamp.org/python/list-pop
* https://guide.freecodecamp.org/python/list-sort-method

![image](https://user-images.githubusercontent.com/37357891/46353437-cf88ed80-c679-11e8-8124-dca4b9cee926.png)

![image](https://user-images.githubusercontent.com/37357891/46353491-f0e9d980-c679-11e8-9007-5bc23c8741d2.png)

The following are related to strings-
* https://guide.freecodecamp.org/python/how-to-convert-strings-into-integers-in-python
* https://guide.freecodecamp.org/python/string-join-method
* https://guide.freecodecamp.org/python/string-replace-method
* https://guide.freecodecamp.org/python/string-split-method
* https://guide.freecodecamp.org/python/string-strip-method

As you see this are related topics but they are in different directory. If this could be in a directory like https://guide.freecodecamp.org/python/data-structures - the hierarchy is  clear in the navigation.
![image](https://user-images.githubusercontent.com/37357891/46353093-fabf0d00-c678-11e8-98ae-66d24a57a66b.png)

Some other topics like python web frameworks, virtual envs related stuffs also are scattered.

**Comment by shamamaz** [comment]
Can this issue be closed based on the PR merged above?

**Comment by Felix-Raj** [comment]
That seems to solve it. Great ㊗️
