### ISSUE TITLE
complete git revert article.

### ISSUE THREAD

**Issue by Rupeshiya** [freeCodeCamp/guide#8756]
git revert article is not there in https://guide.freecodecamp.org/git/git-revert

---

> ✅️ By submitting this issue, I have verified the following

- [ ] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Rupeshiya** [comment]
I would like to complete this .

**Comment by amandeepmittal** [comment]
Since the PR is merged, I am closing this issue.
