### ISSUE TITLE
freecodecamp/guide-Mathematics

### ISSUE THREAD

**Issue by Naba7** [freeCodeCamp/guide#8768]
In the index.md file of mathematics, I think its absurd (irked me actually) to just describe fibonacci series or generating functions. To create interest in his diverse field the index file may include some questions or some algorithms. Just a suggestion.
---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by amandeepmittal** [comment]
You can always open a PR if you think it needs more information on the subject.

**Comment by mUtterberg** [comment]
@amandeepmittal would it be ok to add links to additional learning resources specifically for math, even if they aren't Free Code Camp pages? This site is great for coding content, but there are some REALLY good explanations on math-specific learning resources out there.
