### ISSUE TITLE
Unintended PR merge

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/guide#8901]
This emrged PR https://github.com/freeCodeCamp/guide/pull/8678 added a new folder in the `src` directory as `src/java` which was unintended.
This PR https://github.com/freeCodeCamp/guide/pull/8706 undos that change. 
If any collaborator could fix this? Thanks.
cc: @Asjas @amandeepmittal @Bouncey

**Comment by Asjas** [comment]
@ezioda004 Thanks for opening the issue. :100: 

I have merged PR #8706 and that file has now been removed.
