### ISSUE TITLE
Testing with Chai - Assert Equality - Bug in test cases

### ISSUE THREAD

**Issue by SpiritusSancti5** [freeCodeCamp/guide#9227]
Insert description of issue here

Output i get after submitting:
// running tests
expected 'failed' to equal 'passed'
// tests completed

The only X marked item is :
"All tests should pass"
----

EDIT: NVM, solved the problem

---

> ✅️ By submitting this issue, I have verified the following

- [ ] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [ ] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Hi @SpiritusSancti5 

Please don't open issues about the freeCodeCamp repo on this repo.
