### ISSUE TITLE
Duplicate Lines in Code

### ISSUE THREAD

**Issue by Felix-Raj** [freeCodeCamp/guide#9305]
In the 'Your First Program in C++' example in https://guide.freecodecamp.org/cplusplus , the first two line are duplicated.

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
This has been [fixed](https://github.com/freeCodeCamp/guide/blob/master/src/pages/cplusplus/index.md) in #8940.

Closing this issue as it has been resolved.
