### ISSUE TITLE
Issue with deplow/netlify

### ISSUE THREAD

**Issue by Vagisha16** [freeCodeCamp/guide#9468]
I tried to do a PR twice but the checks were failing. When I looked into details I found that both Travis-CI and yarn cases were failing for all the PRs for last 10 or so hours [as of 4th October]. The Travis issue was a trivial one which I changed and generated a PR again. Now it's showing an error in Deploy/netlify which I guess is in the naming section of GraphQL in "gatsby-node.js" 

You can view the log [here](https://docs.google.com/document/d/1XDVRuYUhpTiQFL9SiuVOaPeu1-z-hRI4i4HEmCGDBSE/edit?usp=sharing)
or  [here](https://app.netlify.com/sites/guide/deploys/5bb585efc6aed67df1a28901)

I hope these are enough details. Otherwise you can just go to the logs of any pull request and check it out.

This issue needs to be sorted because there are many Pull Requests stuck into error codes because of this.
---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by eonmilu** [comment]
There's a file at "freeCodeCamp/guide/src/pages/javascript/template-literals.md" that causes the error. commit bce26a82e9 made by Derek Allred.

**Comment by Asjas** [comment]
@eonmilu Yes we are aware of the file name that is causing the error. There is a PR from @Bouncey that will fix it.

**Comment by Asjas** [comment]
The netlify build has been fixed in #10026. Closing this issue.
