### ISSUE TITLE
Use the strong Tag to Make Text Bold

### ISSUE THREAD

**Issue by Liberty66** [freeCodeCamp/guide#9824]
lesson : Applied Visual Design: Use the strong Tag to Make Text Bold
Requirement N3: "The strong tag should wrap around the words Stanford University." 
action - expected (<strong>Stanford` University.</strong>)
result - unexpected --> (check the screenshot below):
<img width="1005" alt="screen shot 2018-10-06 at 8 45 43 pm" src="https://user-images.githubusercontent.com/42155769/46578077-22301580-c9aa-11e8-9a9f-1e81b242d096.png">

---

**Comment by rkaranam** [comment]
Only words **Stanford University** should be inside <strong> tag. There is a **.** next to words "Stanford University". Moving **.** outside the <strong> tag passes the test.

**Comment by Asjas** [comment]
Hi @Liberty66 

Please don't use `Github Issues` for help. Please use the `freeCodeCamp Gitter` or `freeCodeCamp forum` for help.
