### ISSUE TITLE
JQUERY: jQuery Event Method article is about Bootstrap grid

### ISSUE THREAD

**Issue by GK-Hynes** [freeCodeCamp/guide#9888]
The content of jQuery Event Method article is entirely about Bootstrap grid. Perhaps the wrong file got committed. 

https://github.com/freeCodeCamp/guide/blob/master/src/pages/jquery/jquery-event-method/index.md

---

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by skprabhanjan** [comment]
@Asjas , I can change this but can you help me understand this more as to what needs to added , because there are lots of event handlers in JQuery (https://api.jquery.com/category/events/)

**Comment by Asjas** [comment]
I don't know what event handlers should be added. But you can reset the page to a `stub` initially just to get the bootstrap article out.
