### ISSUE TITLE
Update to Bootstrap4

### ISSUE THREAD

**Issue by KanchanThareja** [freeCodeCamp/guide#9971]
Switch from Bootstrap3 to Bootstrap4

**Comment by Asjas** [comment]
Hi @KanchanThareja 

Why was this issue opened? Is it addressing something specific?

**Comment by Asjas** [comment]
Hi @Bouncey and @QuincyLarson 

Are we going to update the `Guide` from Bootstrap 3 to Bootstrap 4?

**Comment by Bouncey** [comment]
No, I am pretty sure we are not. Thanks for asking the question @KanchanThareja @Asjas 

We are however looking into the possibility of creating our own component library, but it is a long way down the road.
