### ISSUE TITLE
Animation-timing-function CSS

### ISSUE THREAD

**Issue by Fasara** [freeCodeCamp/guide#9991]
Absolute beginner here! 
I'm stuck with the bezier curve. 
Can anyone tell me what am I doing wrong? 

Thanks!
----------------------
<style>
  .balls{
    border-radius: 50%;
    position: fixed;
    width: 50px;
    height: 50px;
    margin-top: 50px;
    animation-name: bounce;
    animation-duration: 2s;
    animation-iteration-count: infinite;
  }
  #red {
    background: red;
    left: 27%;
    animation-timing-function: cubic-bezier (0, 0, 0.58, 1);
  }
  #blue {
    background: blue;
    left: 56%;
    animation-timing-function: ease-out;
  }
  @keyframes bounce {
    0% {
      top: 0px;
    }
    100% {
      top: 249px;
    }
  }
</style>
<div class="balls" id= "red"></div>
<div class="balls" id= "blue"></div>

------------------------------------

> ✅️ By submitting this issue, I have verified the following

- [x] [Checked](https://github.com/freeCodeCamp/guides/issues?q=is%3Aissue+is%3Aclosed) to see if the issue has already been discussed before. 🤔️
- [x] *If* proposing new content to be added, made sure enough details were provided. 🔍️

**Comment by Asjas** [comment]
Hi @Fasara 

Please don't use Github issues for help on challenges.

Please use the [freeCodeCamp forum](https://forum.freecodecamp.org/) or the [Gitter FrontEndHelp](https://gitter.im/FreeCodeCamp/HelpFrontEnd) rooms for help on challenges.
